CREATE TABLE `spider`.`houses` (
  `id` INT NOT NULL,
  `province` VARCHAR(10) NULL,
  `city` VARCHAR(10) NULL,
  `district` VARCHAR(10) NULL,
  `bizDistrict` VARCHAR(10) NULL,
  `building` VARCHAR(20) NULL,
  `address` VARCHAR(10) NULL,
  `houseType` VARCHAR(10) NULL,
  `area` VARCHAR(10) NULL,
  `floor` VARCHAR(10) NULL,
  `orientation` VARCHAR(10) NULL,
  `fitment` VARCHAR(10) NULL,
  `phone` VARCHAR(20) NULL,
  `phonePic` BLOB NULL,
  `title` VARCHAR(45) NULL,
  `housecol` DECIMAL NULL,
  `publisher` VARCHAR(10) NULL,
  `thumbnail` BLOB NULL,
  `href` VARCHAR(255) NULL,
  `category` VARCHAR(10) NULL,
  `convenience` VARCHAR(10) NULL,
  `source` VARCHAR(10) NULL,
  `publishDate` DATE NULL,
  PRIMARY KEY (`id`));
