/*
 出租热点城市
 * */
var hotspots = {
    'hot_58': [
        'http://bj.58.com/chuzu/',
        'http://sh.58.com/chuzu/',
        'http://gz.58.com/chuzu/',
        'http://sz.58.com/chuzu/',
        'http://cd.58.com/chuzu/',
        'http://hz.58.com/chuzu/',
        'http://nj.58.com/chuzu/',
        'http://tj.58.com/chuzu/',
        'http://wh.58.com/chuzu/',
        'http://cq.58.com/chuzu/'
    ],
    'hot_ganji':[
        'http://bj.ganji.com/',
        'http://sh.ganji.com/',
        'http://gz.ganji.com/',
        'http://sz.ganji.com/',
        'http://wh.ganji.com/',
        'http://nj.ganji.com/',
        'http://tj.ganji.com/',
        'http://hz.ganji.com/'
    ],
    'hot_soufun':[
        'http://zu1.fang.com/',
        'http://zu.sh.fang.com/',
        'http://zu.gz.fang.com/',
        'http://zu.sz.fang.com/',
        'http://zu.tj.fang.com/',
        'http://zu.suzhou.fang.com/',
        'http://zu.hz.fang.com/',
        'http://zu.cd.fang.com/',
        'http://zu.cq.fang.com/',
        'http://zu.nanjing.fang.com/',
        'http://zu.wuhan.fang.com/',
        'http://zu.dl.fang.com/',
        'http://zu.qd.fang.com/',
        'http://zu.xian.fang.com/',
        'http://zu.cs.fang.com/'
    ],
    'hot_anjuke':[
        'http://beijing.anjuke.com/',
        'http://shanghai.anjuke.com/',
        'http://guangzhou.anjuke.com/',
        'http://shenzhen.anjuke.com/',
        'http://chengdu.anjuke.com/',
        'http://nanjing.anjuke.com/',
        'http://tianjin.anjuke.com/',
        'http://hangzhou.anjuke.com/'
    ]
};